version: "2.32.0"

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
    - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
    volumes:
      - ./:/src/app
